global:
  scrape_interval: 2s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090
 - job_name: mysql_exporter
   static_configs:
    - targets:
       - mysql-exporter:9104
 - job_name: nginx_exporter
   static_configs:
    - targets:
       - nginx-exporter:9113
 - job_name: node_exporter
   static_configs:
    - targets:
       - node-exporter:9100